FROM asoliev/deep-learning:dev
ARG LOC=../setup/requirements2.txt
COPY requirements.txt $LOC
RUN python3 -m pip install -r $LOC
EXPOSE 8888
CMD [ \
  "jupyter", \
  "notebook", \
  "--allow-root", \
  "--no-browser", \
  # WARNING: this removes any authentication requirements:
  "--NotebookApp.token=''", \
  "--NotebookApp.password=''" \
]
